[package]
name = "chip8-rs"
version = "0.1.0"
authors = ["hulufei <ihulufei@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
crossterm = "0.20"

[dev-dependencies]
insta = "1.7.1"
